# Generated by Django 5.1 on 2024-09-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mastero_interiors', '0002_remove_blogpost_image_url_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
